;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/example]
width = 100%
height = 30px
radius = 0

; dpi = 96

background = #00000000
foreground = ${colors.foreground}

line-size = 3pt

border-size = 7pt
border-color = #00000000

padding-left = 0
padding-right = 0

format-padding = 2

font-0 = Iosevka Nerd Font:size=8;2

modules-left = systray sep xworkspaces sep polywins sep xwindow
modules-center = memory cpu backlight filesystem
modules-right = bat-percentage powerprofiles pulseaudio wlan wattage battery battery2 date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

fixed-center = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/systray]
type = internal/tray

#format-margin = 8pt
# tray-spacing = 16pt
format-background = #ffffff
tray-background = #ffffff
tray-padding = 6
tray-spacing = 2

[module/xworkspaces]
type = internal/xworkspaces

label-active = %index%
label-active-background = #f48fb1 
label-active-foreground = #000000 
label-active-padding = 2

label-occupied = %index%
label-occupied-padding = 2
label-occupied-foreground = #000000 
label-occupied-background = #ffffff 

label-urgent = %index%
label-urgent-background = #f48fb1
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = #000000 
label-empty-background = #ffffff 
label-empty-padding = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:20:...%
label-background = #ffffff
label-foreground = #000000
label-padding = 2

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = 󰋊  %percentage_used%%
label-mounted-background = #51c4f4
label-mounted-padding = 2
label-mounted-foreground = #ffffff


[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%

label-muted = muted
#label-volume-foreground = #ffffff
#label-muted-foreground = #ffffff
#label-muted-background = #ec407a

format-volume-padding = 2
format-volume-background = #ec407a
format-volume-foreground = #ffffff


format-muted-padding = 2
format-muted-background = #ec407a
format-muted-foreground = #ffffff

ramp-volume-0 = " "
ramp-volume-1 = " "
ramp-volume-2 = " "

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
label = %percentage_used:2%%
format-padding = 2
format-background = #51c4f4
format-foreground = #ffffff

[module/cpu]
type = internal/cpu
interval = 5
format-prefix = " "
label = %percentage:2%%
format-background = #5bcefa
format-foreground = #ffffff
format-padding = 2

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = disconnected
format-background = #e91e63

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = 󰖩  %essid%
format-connected-padding = 2
format-connected-background = #e91e63
format-connected-foreground = #ffffff
format-disconnected-foreground = #ffffff
format-disconnected-padding = 2
format-disconnected-background = #e91e63

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %I:%M %p
date-alt = %Y-%m-%d %H:%M:%S

label =   %date%
label-foreground = #ffffff
format-background = #c2185b
format-padding = 2


[module/polywins]
type = custom/script
exec = ~/.config/polybar/scripts/polywins.sh 2>/dev/null
format = <label>
label = %output%
label-padding = 1
label-background = #ffffff
label-foreground = #000000
tail = true

[module/wattage]
type = custom/script
exec = wattage.sh
format = <label>
label = %output%
label-padding = 2
label-background = #d81b60
label-foreground = #ffffff
interval = 5

[module/powerprofiles]
type = custom/script
exec = powerprofilesctl get
format = <label>
label = %output%
label-padding = 2
label-background = #f54882
label-foreground = #ffffff
interval = 5
click-left = powertoggle.sh

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
full-at = 99

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT1
adapter = ACAD

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 2

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging> <label-charging>
format-charging-background = #d81b60
format-charging-foreground = #ffffff 
format-charging-padding = 2

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = #d81b60
format-discharging-padding = 2
format-discharging-foreground = #ffffff 

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
format-full = <label-full>
format-full-prefix = " "
format-full-prefix-font = 2
format-full-background = #d81b60 
format-full-foreground = #ffffff 
format-full-padding = 2

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = BAT1: %percentage%% %output%

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = BAT1: %percentage%% 

; Available tokens:
;   %percentage% (default)
label-full = " Full"

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
ramp-capacity-font = 2

; Only applies if <bar-capacity> is used
;bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = " "
animation-charging-1 = " "
animation-charging-2 = " "
animation-charging-3 = " "
animation-charging-4 = " "
animation-charging-font = 2

; Framerate in milliseconds
animation-charging-framerate = 750

[module/battery2]
type = internal/battery

; This is useful in case the battery never reports 100% charge
full-at = 99

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 2

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging> <label-charging>
format-charging-background = #d81b60
format-charging-foreground = #ffffff 
format-charging-padding = 2

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = #d81b60
format-discharging-padding = 2
format-discharging-foreground = #ffffff 

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
format-full = <label-full>
format-full-prefix = " "
format-full-prefix-font = 2
format-full-background = #d81b60 
format-full-foreground = #ffffff 
format-full-padding = 2

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = BAT0: %percentage%%

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = BAT0: %percentage%%

; Available tokens:
;   %percentage% (default)
label-full = " Full"

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
ramp-capacity-font = 2

; Only applies if <bar-capacity> is used
;bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-font = 2

; Framerate in milliseconds
animation-charging-framerate = 750
[settings]
screenchange-reload = true
pseudo-transparency = true

[module/bat-percentage]
type = custom/script
exec = power.sh
interval = 5
format = <label>
label = %output%%  
format-background = #d81b60 
format-foreground = #ffffff
format-padding = 2

[module/sep]
type = custom/text
content = " "

[module/backlight]
;type = internal/xbacklight
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
;card = intel_backlight
card = intel_backlight

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <ramp> <label>
format-background = #5bcefa
format-foreground = #ffffff
format-padding = 2

enable-scroll = true

; Available tokens:
;   %percentage% (default)
label = %percentage%%

; Only applies if <ramp> is used
ramp-0 = " "
ramp-1 = " "
ramp-2 = " "
ramp-3 = " "
ramp-4 = " "
ramp-5 = " "
ramp-6 = " "
ramp-7 = " "
ramp-8 = " "
ramp-font = 2

; vim:ft=dosini
